version: "3.1"
services:
  redis:
    image: redis
    restart: always
    networks:
      - grouparoo_backend.local

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grouparoo_docker
    networks:
      - grouparoo_backend.local

  grouparoo-web:
    build: ./
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql://postgres:password@db:5432/grouparoo_docker
      WEB_SERVER: "true"
      SCHEDULER: "false"
      WORKERS: 0
      SERVER_TOKEN: "default-server-token"
    depends_on:
      - db
      - redis
    networks:
      - grouparoo_frontend.local
      - grouparoo_backend.local

  grouparoo-worker:
    build: ./
    restart: always
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql://postgres:password@db:5432/grouparoo_docker
      WEB_SERVER: "false"
      SCHEDULER: "true"
      WORKERS: 10
      SERVER_TOKEN: "default-server-token"
    depends_on:
      - db
      - redis
      - grouparoo-web
    networks:
      - grouparoo_frontend.local
      - grouparoo_backend.local

networks:
  grouparoo_frontend.local:
  grouparoo_backend.local:
