apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grouparoo-example-app.fullname" . }}
  labels:
    {{- include "grouparoo-example-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "grouparoo-example-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "grouparoo-example-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "grouparoo-example-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
          - name: PORT
            value: '3000'
          - name: WEB_SERVER
            value: 'true'
          - name: SCHEDULER
            value: 'true'
          - name: WORKERS
            value: '1'
          - name: SERVER_TOKEN
            value: default-server-token
          - name: DATABASE_URL
            value: postgresql://postgres:password@{{ template "postgresql.fullname" . }}-postgresql:5432/grouparoo_docker # postgresql://postgres:password@db:5432/grouparoo_docker
          - name: REDIS_URL
            value: redis://{{ include "grouparoo-example-app.fullname" . }}-redis-master:6379/0 # redis://redis:6379/0
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
