apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file=docker-compose.published.yml --build=local --out=helm --chart
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: grouparoo-web
  name: grouparoo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grouparoo-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file=docker-compose.published.yml --build=local --out=helm --chart
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/grouparoo-backend.local: "true"
        io.kompose.network/grouparoo-frontend.local: "true"
        io.kompose.service: grouparoo-web
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://postgres.grouparoo-web:password@db:5432/grouparoo_docker
            - name: PORT
              value: "3000"
            - name: REDIS_URL
              value: redis://redis.grouparoo-web:6379/0
            - name: SCHEDULER
              value: "false"
            - name: SERVER_TOKEN
              value: default-server-token
            - name: WEB_SERVER
              value: "true"
            - name: WORKERS
              value: "0"
          image: grouparoo/app-example
          name: grouparoo-web
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
