name: update

on:
  push:
    branches: [master]
  schedule:
    - cron: "5 5 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'grouparoo/app-example' }}

    steps:
      - uses: actions/checkout@master
      - run: sudo npm install -g npm-check-updates
      - run: npm-check-updates -u
      - run: npm install
      - uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Updating Packages
          commit_user_name: Grouparoo Bot
          commit_user_email: hello@grouparoo.com
          commit_author: Grouparoo Bot <hello@grouparoo.com>
          branch: ${{ github.head_ref }}
